
aws:
   access_key_id: "AKIA4SKK4RFG72HXIG7B"
   secret_access_key: "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"

Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: 6DpRGz3Xg8/l0inSqHn+Vndvjeq6zSlHD7lGKtRO2ZzIP3Czo2SuATx81RFWfKZsfaxRxpF3a4gM8HhtNJ7Y0Q+9Jw1RxVjNWlMk0mkL3UiXKuvjHLHmKS8Aualynpa73d3M78e4e3EZEjYUT/l14+kaYw440dXfjB1Zl4vpKK3+dWzD3aMKG9fA51nbJi6AKl1WIvfB7abbd8C2/IH2MUp65yAnyMLyDYAQXa8KlpcJ68UgZ1CeaoyzywtF7uh3kDXlGpA1CWL9HSgI9nobxBZkH+iGye3+3zbuLp/B9xQ4HPq6ZZ7OHhOQzvf6egE7rpUsqohQX4RhXOZRREZCwaexat+kO2OmETU8CQfqK1PH2eQ75EuqnhbEfiQMZSop2k9dxHREmgee8euNsjcOD7/tY0Scwu7oCXeq--AvyRWadM3qwZbgVQ--2S9oT6hnbj6aNauUPFwZ2Q==